name: TSB-new
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - colorama=0.4.6
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - gh=2.69.0
  - iniconfig=2.0.0
  - ipdb=0.13.13
  - ipython=8.35.0
  - jedi=0.19.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnsl=2.0.1
  - libsqlite=3.46.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - openssl=3.5.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pluggy=1.5.0
  - prompt-toolkit=3.0.50
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyproject_hooks=1.2.0
  - pytest=8.3.5
  - python=3.10.14
  - python_abi=3.10
  - readline=8.2
  - setuptools=61.2.0
  - sqlite=3.38.5
  - stack_data=0.6.3
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.37.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - arch==7.2.0
      - astunparse==1.6.3
      - build==1.2.2.post1
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.0.12
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - hurst==0.0.5
      - idna==3.10
      - joblib==1.4.2
      - keras==3.9.2
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - llvmlite==0.44.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - namex==0.0.8
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==2.1.3
      - opt-einsum==3.4.0
      - optree==0.15.0
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.1.0
      - protobuf==5.29.4
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.8.0
      - requests==2.32.3
      - rich==14.0.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - statsmodels==0.14.4
      - stumpy==1.13.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.0.1
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tsfresh==0.21.0
      - tslearn==0.6.3
      - tzdata==2025.2
      - urllib3==2.4.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
